### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2

### ISSUE THREAD

**Issue by seihtam** [malice-plugins/pescan#6]
Scanning same file as in #4 results in:

```
2018-12-06 10:04:47,747 - __main__ - ERROR - failed to run malice plugin: pescan
Traceback (most recent call last):
  File "/usr/sbin/pescan", line 122, in scan
    malice_scan['results']['markdown'] = json2markdown(pe_results)
  File "/usr/sbin/utils/__init__.py", line 74, in json2markdown
    return Template(f.read()).render(exe=json_data)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 62, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10: ordinal not in range(128)
DIALOG_TITLE: FILE_STRING
SUCCESS
PE: STRINGS - RT_DIALOG (id:0x6e - lang_id:0x0409 [English-United States])
DIALOG_TITLE: FILE_STRING
BUTTON: FILE_STRING
BUTTON: FILE_STRING
SUCCESS
PE: STRINGS - RT_DIALOG (id:0x6f - lang_id:0x0409 [English-United States])
DIALOG_TITLE: FILE_STRING
BUTTON: FILE_STRING
BUTTON: FILE_STRING
BUTTON: FILE_STRING
SUCCESS
PE: STRINGS - RT_DIALOG (id:0x71 - lang_id:0x0409 [English-United States])
DIALOG_TITLE: FILE_STRING
BUTTON: FILE_STRING
SUCCESS
```

**Comment by seihtam** [comment]
By the way you can download the file i'm scanning here: https://the.earth.li/~sgtatham/putty/latest/w64/putty.exe

**Comment by blacktop** [comment]
I probably need to update to python3 inside the plugin these look like unicode errors UTF-8

**Comment by blacktop** [comment]
@seihtam this is working now for me.  Can you pull a new version and test again please?

Again, thank you for all your help!

**Comment by seihtam** [comment]
I'll be able to test it in the start of February.

Thanks for all your work on malice!

**Comment by seihtam** [comment]
Tested it and can confirm it's also working for me now!
